version: '3.9'

services:
  api_express:
    container_name: api_express
    image: node:16
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=limac
      - POSTGRES_PASSWORD=1923
      - POSTGRES_DB=defalutdb
    